name: Continuous monitoring of distribution channels
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 */1 * * *'

jobs:
  pull-agent:
    name: Pull X-Ray .NET agent from Github
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Pull X-Ray .NET agent from Github
        id: distribution-availability-github
        run: wget https://github.com/aws/aws-xray-dotnet-agent/archive/refs/tags/v2.9.0-beta.1.zip

      - name: Publish metric on X-Ray .NET agent distribution availability (Github)
        if: ${{ always() }}
        run: |
          if [[ "${{ steps.distribution-availability-github.outcome }}" == "failure" ]]; then
            aws cloudwatch put-metric-data --metric-name XRayDotnetAgentGithubDistributionUnavailability --dimensions failure=rate --namespace MonitorAgent --value 1 --timestamp $(date +%s)
          else
            aws cloudwatch put-metric-data --metric-name XRayDotnetAgentGithubDistributionUnavailability --dimensions failure=rate --namespace MonitorAgent --value 0 --timestamp $(date +%s)
          fi
